const blogPost = [
    {
        "title": "Exploring South Africa's beauty",
        "date": '2021/13/08',
        "author": "Marc",
        "article": "South Africa, a land of diverse landscapes and cultures, promises an adventure like no other. As you set foot on this captivating country, you are greeted by the rugged beauty of Table Mountain overlooking Cape Town and the golden beaches of Durban's shoreline. South Africa's rich tapestry unfolds before your eyes Venture into the heart of the country, and you'll find the stunning Kruger National Park, home to the Big Five and countless other wildlife wonders. The thrill of a safari adventure here is unparalleled, as you witness lions basking in the golden light and elephants wandering through the savannah.The vibrant pulse of Johannesburg and the historical charm of Pretoria take you on a journey through the nation's complex history. Robben Island, where Nelson Mandela was imprisoned, serves as a poignant reminder of the country's struggle for freedom.South Africa's cultural mosaic comes to life in the bustling streets of Soweto, where vibrant art, music, and dance reflect the resilience of the people. The cuisine is a tantalizing blend of flavors, with dishes like bobotie and boerewors sausage tempting your taste buds.In South Africa, every moment is a celebration of life, nature, and unity. It's a destination that leaves an indelible mark on your soul, a place where adventure, history, and culture converge, creating memories that last a lifetime.",
        "imageUrl": "https://images.pexels.com/photos/4840246/pexels-photo-4840246.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        "dining": "Dining: Delight in the rich flavors of South African cuisine with a visit to Mzansi in Soweto, a local gem known for its warm hospitality and traditional dishes like bobotie, a tantalizing blend of spices, minced meat, and baked egg-based topping.",
        "adventure": "Adventures: For the ultimate thrill, take a daring hike up the Drakensberg Mountains, where the Amphitheatre's cliffs plunge dramatically. It's a journey for the intrepid, offering breathtaking views and a sense of achievement.",
        "shopping": "Shopping: In Cape Town, the V&A Waterfront offers a shopping haven with a blend of local crafts and international brands. It's a great place to find unique souvenirs, jewelry, and African artwork."
    },
    {
        "title": "Exploring South Africa's beauty",
        "date": '2021-13-10',
        "author": "Marc",
        "article": "South Africa, a land of diverse landscapes and cultures, promises an adventure like no other. As you set foot on this captivating country, you are greeted by the rugged beauty of Table Mountain overlooking Cape Town and the golden beaches of Durban's shoreline. South Africa's rich tapestry unfolds before your eyes Venture into the heart of the country, and you'll find the stunning Kruger National Park, home to the Big Five and countless other wildlife wonders. The thrill of a safari adventure here is unparalleled, as you witness lions basking in the golden light and elephants wandering through the savannah.The vibrant pulse of Johannesburg and the historical charm of Pretoria take you on a journey through the nation's complex history. Robben Island, where Nelson Mandela was imprisoned, serves as a poignant reminder of the country's struggle for freedom.South Africa's cultural mosaic comes to life in the bustling streets of Soweto, where vibrant art, music, and dance reflect the resilience of the people. The cuisine is a tantalizing blend of flavors, with dishes like bobotie and boerewors sausage tempting your taste buds.In South Africa, every moment is a celebration of life, nature, and unity. It's a destination that leaves an indelible mark on your soul, a place where adventure, history, and culture converge, creating memories that last a lifetime.",
        "imageUrl": "https://images.pexels.com/photos/1790573/pexels-photo-1790573.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        "dining": "Dining: Delight in the rich flavors of South African cuisine with a visit to Mzansi in Soweto, a local gem known for its warm hospitality and traditional dishes like bobotie, a tantalizing blend of spices, minced meat, and baked egg-based topping.",
        "adventure": "Adventures: For the ultimate thrill, take a daring hike up the Drakensberg Mountains, where the Amphitheatre's cliffs plunge dramatically. It's a journey for the intrepid, offering breathtaking views and a sense of achievement.",
        "shopping": "Shopping: In Cape Town, the V&A Waterfront offers a shopping haven with a blend of local crafts and international brands. It's a great place to find unique souvenirs, jewelry, and African artwork."
    }
];

module.exports = blogPost;